image: registry.gitlab.com/orobardet/gitlab-ci-linter/build

stages:
  - vendors
  - checks
  - build

before_script:
  - cd $GOPATH/src
  - ln -s $CI_PROJECT_DIR
  - cd $(basename $CI_PROJECT_DIR)

get vendors:
  stage: vendors
  script:
    - dep ensure
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    paths:
      - vendor/
    expire_in: 1 hour


gofmt:
  stage: checks
  script: gofmt -l -e $(find . -name "*.go" -type f -not -path "./vendor/*")

govet:
  stage: checks
  script: go vet

build:
  stage: build
  dependencies:
    - get vendors
  script:
    - make
