image: registry.gitlab.com/orobardet/gitlab-ci-linter/build

stages:
  - vendors
  - build

get vendors:
  stage: vendors
  script:
    - dep ensure
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    paths:
      - vendor/
    expire_in: 1 hour

build:
  stage: build
  dependencies:
    - get vendors
  script:
    - make
